# Stores logs from all agents in the pipeline
logs = []

def log(agent_name, input_text, output_text, issues=None):
    logs.append({
        "agent": agent_name, #name of the agent
        "input": input_text, #text received by the agent
        "output": output_text, #text generated by agent
        "issues": issues or [] #issues found by the agent
    })
#Returns all stored logs and Useful for viewing the complete agent workflow
def get_logs():
    return logs